from enum import Enum


class GraspMode(Enum):
    """Enumeration of the grasp mode"""
    GRASP = 1
    F1F2_GRASP = 2
    F1F3_GRASP = 3
    F2F3_GRASP = 4
    PARALLEL_GRASP = 5
    ENVELOP_GRASP = 6


"""Enumeration of the Delto 3f"""


class Delto3F(Enum):
    MOTOR_NUM = 12


class Delto3FCoils(Enum):
    """Enumeration of coils addresses of the Delto 3f"""
    MOVING_AVERAGE_FILTER = 0
    GRASP = 1
    JOINT_CUSTOM_MODE = 2
    EEPROM_WRITE = 3


class Delto3FHoldingRegisters(Enum):
    """Enumeration of the holding registers addresses of the Delto 3f"""
    RS485_BAUDRATE = 0

    MODBUS_SLAVE_ID = 1

    ETHERNET_IP_CLASS_A = 2
    ETHERNET_IP_CLASS_B = 3
    ETHERNET_IP_CLASS_C = 4
    ETHERNET_IP_CLASS_D = 5

    ETHERNET_SUBNET_MASK_A = 6
    ETHERNET_SUBNET_MASK_B = 7
    ETHERNET_SUBNET_MASK_C = 8
    ETHERNET_SUBNET_MASK_D = 9

    ETHERNET_GATEWAY_A = 10
    ETHERNET_GATEWAY_B = 11
    ETHERNET_GATEWAY_C = 12
    ETHERNET_GATEWAY_D = 13

    ETHERNET_PORT = 14

    MOTOR1_PGAIN = 15
    MOTOR2_PGAIN = 16
    MOTOR3_PGAIN = 17
    MOTOR4_PGAIN = 18
    MOTOR5_PGAIN = 19
    MOTOR6_PGAIN = 20
    MOTOR7_PGAIN = 21
    MOTOR8_PGAIN = 22
    MOTOR9_PGAIN = 23
    MOTOR10_PGAIN = 24
    MOTOR11_PGAIN = 25
    MOTOR12_PGAIN = 26

    MOTOR1_DGAIN = 27
    MOTOR2_DGAIN = 28
    MOTOR3_DGAIN = 29
    MOTOR4_DGAIN = 30
    MOTOR5_DGAIN = 31
    MOTOR6_DGAIN = 32
    MOTOR7_DGAIN = 33
    MOTOR8_DGAIN = 34
    MOTOR9_DGAIN = 35
    MOTOR10_DGAIN = 36
    MOTOR11_DGAIN = 37
    MOTOR12_DGAIN = 38

    MOTOR1_OFFSET = 51
    MOTOR2_OFFSET = 52
    MOTOR3_OFFSET = 53
    MOTOR4_OFFSET = 54
    MOTOR5_OFFSET = 55
    MOTOR6_OFFSET = 56
    MOTOR7_OFFSET = 57
    MOTOR8_OFFSET = 58
    MOTOR9_OFFSET = 59
    MOTOR10_OFFSET = 60
    MOTOR11_OFFSET = 61
    MOTOR12_OFFSET = 62

    START_MOTION = 63
    MOTION_STEP = 64

    IO_LOW_TORQUE = 65
    IO_HIGH_TORQUE = 66

    GRASP_MODE = 67
    GRASP_TORQUE = 68

    MOVING_AVERAGE_FILTER = 69

    MOTION_SAVE = 70
    MOTION_LOAD = 71

    MOTOR1_TARGET_POSITION = 72
    MOTOR2_TARGET_POSITION = 73
    MOTOR3_TARGET_POSITION = 74
    MOTOR4_TARGET_POSITION = 75
    MOTOR5_TARGET_POSITION = 76
    MOTOR6_TARGET_POSITION = 77
    MOTOR7_TARGET_POSITION = 78
    MOTOR8_TARGET_POSITION = 79
    MOTOR9_TARGET_POSITION = 80
    MOTOR10_TARGET_POSITION = 81
    MOTOR11_TARGET_POSITION = 82
    MOTOR12_TARGET_POSITION = 83
    
    # The following is accessible from firmware version 1.5 or higher.
    MOTOR1_FIXED_POSITION = 96
    MOTOR2_FIXED_POSITION = 97
    MOTOR3_FIXED_POSITION = 98
    MOTOR4_FIXED_POSITION = 99
    MOTOR5_FIXED_POSITION = 100
    MOTOR6_FIXED_POSITION = 101
    MOTOR7_FIXED_POSITION = 102
    MOTOR8_FIXED_POSITION = 103
    MOTOR9_FIXED_POSITION = 104
    MOTOR10_FIXED_POSITION = 105
    MOTOR11_FIXED_POSITION = 106
    MOTOR12_FIXED_POSITION = 107

    SAVE_TARGET_POSITION = 108
    TORQUE_LIMIT = 109

class Delto3FInputRegisters(Enum):
    """Enumeration of the input registers addresses of the Delto 3f"""
    PRODUCT_ID = 0
    FIRMWARE_VERSION = 1

    MOTOR1_CURRENT_POSITION = 2
    MOTOR2_CURRENT_POSITION = 3
    MOTOR3_CURRENT_POSITION = 4
    MOTOR4_CURRENT_POSITION = 5
    MOTOR5_CURRENT_POSITION = 6
    MOTOR6_CURRENT_POSITION = 7
    MOTOR7_CURRENT_POSITION = 8
    MOTOR8_CURRENT_POSITION = 9
    MOTOR9_CURRENT_POSITION = 10
    MOTOR10_CURRENT_POSITION = 11
    MOTOR11_CURRENT_POSITION = 12
    MOTOR12_CURRENT_POSITION = 13

    MOTOR1_ELECTRIC_CURRENT = 14
    MOTOR2_ELECTRIC_CURRENT = 15
    MOTOR3_ELECTRIC_CURRENT = 16
    MOTOR4_ELECTRIC_CURRENT = 17
    MOTOR5_ELECTRIC_CURRENT = 18
    MOTOR6_ELECTRIC_CURRENT = 19
    MOTOR7_ELECTRIC_CURRENT = 20
    MOTOR8_ELECTRIC_CURRENT = 21
    MOTOR9_ELECTRIC_CURRENT = 22
    MOTOR10_ELECTRIC_CURRENT = 23
    MOTOR11_ELECTRIC_CURRENT = 24
    MOTOR12_ELECTRIC_CURRENT = 25
